// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/it-interview-prep/CourseRadarLayout.tsx": () => import("../components/mockups/it-interview-prep/CourseRadarLayout.tsx")
};
