/**
 * Seeds the 3 courses that failed in the main seed script:
 *  - Active Directory & LDAP  (Security)
 *  - Playwright & Cypress     (Testing)
 *  - LLM & OpenAI APIs        (AI & ML)
 *
 * Run: ./scripts/node_modules/.bin/tsx scripts/seed-remaining-courses.ts
 */
import { eq } from "drizzle-orm";
import { db, coursesTable, questionsTable } from "@workspace/db";

type Level = "beginner" | "intermediate" | "advanced";
interface Q { level: Level; text: string; options: string[]; correctOptionIndex: number; explanation: string; }
interface CourseData { name: string; slug: string; description: string; icon: string; category: string; questions: Q[]; }

const NEW_COURSES: CourseData[] = [
  // ── Active Directory ──────────────────────────────────────────────────────
  {
    name: "Active Directory & LDAP",
    slug: "active-directory",
    description: "Enterprise identity with Active Directory — domain structure, group policy, authentication protocols, Azure AD/Entra ID, and LDAP administration.",
    icon: "SiMicrosoftazure",
    category: "Security",
    questions: [
      // Beginner
      { level: "beginner", text: "What is Active Directory?", options: ["A file server","Microsoft's directory service for Windows domain networks — manages user accounts, computers, groups, and policies using a hierarchical structure","A backup system","A firewall"], correctOptionIndex: 1, explanation: "AD provides centralised authentication (Kerberos), authorisation, and management of all resources in a Windows domain." },
      { level: "beginner", text: "What is a Domain Controller (DC)?", options: ["A network router","A server running Active Directory Domain Services (AD DS) that stores the directory database, authenticates users, and enforces Group Policy","A DNS server","A DHCP server"], correctOptionIndex: 1, explanation: "Every AD domain needs at least one DC. Multiple DCs provide redundancy via multi-master replication." },
      { level: "beginner", text: "What is an Organizational Unit (OU) in AD?", options: ["A user group","A container object used to organise users, computers, and groups within a domain, to which Group Policy Objects (GPOs) can be linked","A domain","A forest"], correctOptionIndex: 1, explanation: "OUs provide administrative delegation and a structured way to apply GPOs to subsets of domain objects." },
      { level: "beginner", text: "What is Group Policy in Active Directory?", options: ["A user permission","A framework for managing configurations (security settings, software deployment, scripts) applied to users and computers via GPOs linked to OUs/domains","A DNS record","A replication setting"], correctOptionIndex: 1, explanation: "GPOs apply settings from the DC to clients at logon or startup. gpupdate /force immediately applies pending policies." },
      { level: "beginner", text: "What is Kerberos in Active Directory?", options: ["A firewall protocol","The default authentication protocol in AD — uses tickets (TGT, service tickets) issued by the Key Distribution Center (KDC) for SSO across the domain","A DNS record type","A replication protocol"], correctOptionIndex: 1, explanation: "Kerberos provides SSO: log in once, get a TGT, present service tickets to access resources without re-entering credentials." },
      { level: "beginner", text: "What is an AD Security Group vs Distribution Group?", options: ["Identical","Security Groups control access to resources (NTFS permissions, GPOs); Distribution Groups are for email lists only","Distribution Groups control permissions","Security Groups are for email"], correctOptionIndex: 1, explanation: "Security Groups are the AD construct for RBAC — assign them permissions; add users to them." },
      { level: "beginner", text: "What is LDAP?", options: ["A file protocol","Lightweight Directory Access Protocol — an open protocol for querying and modifying directory services like Active Directory","A DNS protocol","An email protocol"], correctOptionIndex: 1, explanation: "LDAP queries AD using distinguished names (DNs): CN=John,OU=Users,DC=corp,DC=com. LDAPS adds TLS encryption." },
      { level: "beginner", text: "What is an AD Forest?", options: ["A server farm","The topmost boundary in Active Directory — a collection of one or more domains sharing a common schema, global catalog, and trust infrastructure","A domain group","A network segment"], correctOptionIndex: 1, explanation: "Forests provide security boundaries. Two-way trusts between forest roots allow users to authenticate across forests." },
      { level: "beginner", text: "What is the Global Catalog (GC) in AD?", options: ["A directory backup","A partial replica of all objects in all domains within a forest, used for logon and cross-domain searches without querying individual domain controllers","A DNS service","A trust type"], correctOptionIndex: 1, explanation: "The GC stores a subset of attributes from all forest objects. UPN logon and Exchange address book lookups use the GC." },
      { level: "beginner", text: "What is Azure AD (Microsoft Entra ID)?", options: ["An on-premises AD version","Microsoft's cloud-based identity platform providing SSO, MFA, Conditional Access, and app registration for SaaS and cloud resources","A file share service","A monitoring tool"], correctOptionIndex: 1, explanation: "Azure AD (now Entra ID) is the cloud counterpart to on-prem AD. Azure AD Connect syncs identities between the two." },
      // Intermediate
      { level: "intermediate", text: "What is Azure AD Connect?", options: ["A VPN tool","A tool that synchronises on-premises Active Directory identities to Azure AD, enabling hybrid identity with SSO across cloud and on-prem","A DNS sync tool","An AD backup"], correctOptionIndex: 1, explanation: "Azure AD Connect syncs users, groups, and password hashes (or enables federation via ADFS) to Entra ID." },
      { level: "intermediate", text: "What is Conditional Access in Azure AD?", options: ["A firewall rule","A policy engine that evaluates signals (user, device, location, app, risk) and enforces access controls (allow, block, require MFA) for app access","A group policy","An LDAP feature"], correctOptionIndex: 1, explanation: "Conditional Access is the zero-trust enforcement point in Entra ID, requiring MFA when risky sign-in signals are detected." },
      { level: "intermediate", text: "What is NTLM and why is Kerberos preferred?", options: ["A DNS protocol","NTLM is an older challenge-response auth protocol; Kerberos is preferred because it provides true SSO, mutual authentication, and no password hash transmission","NTLM is more secure","They are the same"], correctOptionIndex: 1, explanation: "NTLM is vulnerable to pass-the-hash attacks. Kerberos provides delegation and is more efficient for domain resources." },
      { level: "intermediate", text: "What is a Service Principal Name (SPN)?", options: ["A domain name","A unique identifier for a service instance in Kerberos — required for services to receive Kerberos tickets from clients (e.g. HTTP/webserver.corp.com)","A DNS record","A user account type"], correctOptionIndex: 1, explanation: "SPNs are registered against service accounts. Misconfigured SPNs cause Kerberos authentication failures for services." },
      { level: "intermediate", text: "What is AD Replication?", options: ["A backup process","The process by which changes to the AD database (user creation, password changes) are propagated from one DC to all other DCs via multi-master replication","A DNS sync","A GPO application"], correctOptionIndex: 1, explanation: "AD uses a pull model with USNs (Update Sequence Numbers). Replication within a site is fast; between sites uses site link schedules." },
      { level: "intermediate", text: "What is a Trust in Active Directory?", options: ["A security certificate","A relationship between domains/forests allowing users in one domain to authenticate to resources in another — can be one-way or two-way, transitive or explicit","A GPO setting","A DNS record"], correctOptionIndex: 1, explanation: "Forest trusts enable cross-forest authentication. External trusts connect to NT4 or non-transitive domains." },
      { level: "intermediate", text: "What is the SYSVOL folder in AD?", options: ["A system volume","A shared directory on every DC containing GPO templates, scripts, and policy files, replicated via DFSR to all DCs","A user folder","A backup location"], correctOptionIndex: 1, explanation: "SYSVOL is accessed by clients during Group Policy processing. DFSR keeps it synchronised across all DCs." },
      { level: "intermediate", text: "What is Privileged Identity Management (PIM) in Azure AD?", options: ["A VPN feature","A service providing just-in-time (JIT) privileged access to Azure and Entra ID roles — users activate elevated permissions only when needed, with approval and time limits","A password manager","A backup tool"], correctOptionIndex: 1, explanation: "PIM reduces the attack surface by eliminating standing admin access. It provides activation workflows and access reviews." },
      { level: "intermediate", text: "What are AD fine-grained password policies?", options: ["A GUI tool","Password and lockout policies applied to specific groups or users (not just the domain default), using Password Settings Objects (PSOs)","A domain setting","A DNS feature"], correctOptionIndex: 1, explanation: "PSOs allow applying stricter password requirements to privileged users or service accounts than the domain policy." },
      { level: "intermediate", text: "What is an AD Service Account vs Managed Service Account (MSA)?", options: ["Identical","Regular service accounts require manual password management; MSAs (and gMSAs) have auto-rotating passwords managed by AD, eliminating credential management","MSAs are for users","Service accounts are deprecated"], correctOptionIndex: 1, explanation: "Group Managed Service Accounts (gMSAs) extend MSAs to multiple servers — ideal for IIS app pools and scheduled tasks." },
      // Advanced
      { level: "advanced", text: "What is Pass-the-Hash (PtH) and how do you mitigate it?", options: ["A network protocol","An attack where stolen NTLM hashes are used to authenticate without knowing the plaintext password. Mitigate: use Kerberos, enable Protected Users group, implement Credential Guard, disable NTLM","A DNS attack","A GPO exploit"], correctOptionIndex: 1, explanation: "PtH is possible because NTLM auth uses the hash directly. Protected Users group prevents NTLM fallback for privileged accounts." },
      { level: "advanced", text: "What is Kerberoasting?", options: ["A network scan","An attack where an attacker requests Kerberos service tickets for SPNs and cracks them offline to obtain service account passwords","A DNS poisoning","An NTLM attack"], correctOptionIndex: 1, explanation: "Service tickets are encrypted with the service account's password hash. Use long random passwords for service accounts and AES encryption to mitigate." },
      { level: "advanced", text: "What is the KRBTGT account and why is it critical?", options: ["A service account","The account whose password encrypts all Kerberos TGTs in the domain — compromise allows creating forged Golden Tickets with arbitrary privileges","A built-in user","A managed account"], correctOptionIndex: 1, explanation: "A Golden Ticket attack requires the KRBTGT hash. Reset KRBTGT twice after domain compromise (old hash is cached for up to 10 hours)." },
      { level: "advanced", text: "What is AD Tiering (Administrative Tier Model)?", options: ["A GPO structure","A security model separating privileged accounts into Tier 0 (DCs/AD), Tier 1 (servers), and Tier 2 (workstations) — preventing lateral movement from lower to higher tiers","A replication design","A trust model"], correctOptionIndex: 1, explanation: "Tier 0 admins should only log in to Tier 0 systems. PAWs (Privileged Access Workstations) are dedicated to admin tasks." },
      { level: "advanced", text: "What is Microsoft Entra ID Protection?", options: ["A password manager","An AI-driven risk detection service that identifies compromised identities and risky sign-ins, integrating with Conditional Access to enforce MFA or block access","A backup tool","A VPN feature"], correctOptionIndex: 1, explanation: "Entra ID Protection uses Microsoft's threat intelligence to detect impossible travel, leaked credentials, and anonymous IPs." },
      { level: "advanced", text: "What is LDAP injection and how is it prevented?", options: ["A network exploit","An attack inserting malicious LDAP filter syntax into input fields to manipulate directory queries. Prevented by input validation and using parameterised LDAP APIs","An NTLM attack","A replication exploit"], correctOptionIndex: 1, explanation: "Unsanitised input in LDAP filters like (uid=*) can return all users. Escape special characters including null bytes in LDAP queries." },
      { level: "advanced", text: "What is Azure AD Application Proxy?", options: ["A VPN gateway","A service enabling secure remote access to on-premises web apps via Entra ID authentication without a VPN, using an on-premises connector agent","A reverse proxy","A DNS service"], correctOptionIndex: 1, explanation: "App Proxy provides SSO to on-prem apps (IIS, SharePoint) using Entra ID authentication, replacing VPN-based remote access." },
      { level: "advanced", text: "What is DCSync attack?", options: ["A replication configuration","An attack where an account with Replicating Directory Changes permission simulates a DC to pull password hashes for all accounts via the MS-DRSR protocol","A DNS exploit","A GPO attack"], correctOptionIndex: 1, explanation: "DCSync is used by mimikatz to steal the KRBTGT hash and all user credentials. Only DCs and Azure AD Connect should have this permission." },
      { level: "advanced", text: "What is Zero Trust and how does it apply to AD/Entra ID?", options: ["A firewall configuration","A security model that assumes breach — verify every access request explicitly using identity, device compliance, and context rather than network location","An AD trust type","A VPN replacement"], correctOptionIndex: 1, explanation: "Microsoft's Zero Trust pillars: Identity (Entra ID), Device (Intune), Network (Defender for Cloud Apps), Apps, and Data." },
      { level: "advanced", text: "What is the difference between SAML, OAuth 2.0, and OpenID Connect in Entra ID?", options: ["Identical","SAML is XML-based federation (legacy enterprise apps); OAuth 2.0 is an authorisation framework for API access; OIDC extends OAuth 2.0 for authentication with an ID token","SAML is modern","OAuth is for AD only"], correctOptionIndex: 1, explanation: "Modern apps use OIDC (authentication) + OAuth 2.0 (authorisation). SAML remains for legacy SSO. Entra ID supports all three." },
    ],
  },

  // ── Playwright & Cypress ──────────────────────────────────────────────────
  {
    name: "Playwright & Cypress",
    slug: "playwright",
    description: "Modern end-to-end testing — browser automation, selectors, async patterns, network interception, CI integration, and visual testing.",
    icon: "SiPlaywright",
    category: "Testing",
    questions: [
      // Beginner
      { level: "beginner", text: "What is Playwright?", options: ["A web scraper","A Microsoft-developed, open-source end-to-end testing framework for web apps, supporting Chromium, Firefox, and WebKit across multiple languages","A unit testing framework","A CI tool"], correctOptionIndex: 1, explanation: "Playwright provides a single API for cross-browser automation, auto-waits for elements, and has excellent TypeScript support." },
      { level: "beginner", text: "What is Cypress?", options: ["A load testing tool","A JavaScript-native end-to-end testing framework that runs inside the browser alongside the app, providing real-time reloading and a visual test runner","A unit test runner","A backend testing tool"], correctOptionIndex: 1, explanation: "Cypress's architecture (running in-browser) gives it direct access to the DOM, network, and application state." },
      { level: "beginner", text: "What is the key difference between Playwright and Cypress?", options: ["No difference","Playwright supports multiple languages (Python, Java, C#, JS/TS) and multiple browser tabs/windows natively; Cypress is JS/TS only and single-tab within one browser","Cypress is faster always","Playwright requires a browser binary"], correctOptionIndex: 1, explanation: "Playwright uses async/await with proper multi-page/tab support; Cypress uses a synchronous-looking API with automatic retry." },
      { level: "beginner", text: "How do you locate an element in Playwright?", options: ["By CSS only","Using page.locator('selector') which supports CSS, XPath, text content, ARIA roles, and data-testid attributes","By ID only","By class name only"], correctOptionIndex: 1, explanation: "Playwright recommends getByRole(), getByText(), getByTestId() for robust, maintenance-friendly locators." },
      { level: "beginner", text: "How do you click an element in Playwright?", options: ["element.click()","await locator.click()","locator.trigger('click')","page.click(selector) or locator.click()"], correctOptionIndex: 3, explanation: "Both page.click('selector') and locator.click() work. Playwright auto-waits for the element to be actionable." },
      { level: "beginner", text: "What is cy.get() in Cypress?", options: ["A network request","A command querying the DOM for elements matching a CSS selector, returning a chainable Cypress object","A variable getter","A config method"], correctOptionIndex: 1, explanation: "cy.get('button[type=submit]') returns a Cypress chain; .click(), .type(), .should() chain onto it." },
      { level: "beginner", text: "What is cy.intercept() used for in Cypress?", options: ["Blocking URLs","Stubbing and spying on network requests — allows returning mock responses or waiting for requests to complete","A DOM selector","A navigation command"], correctOptionIndex: 1, explanation: "cy.intercept('GET', '/api/users', { fixture: 'users.json' }) returns mock data without hitting the real server." },
      { level: "beginner", text: "What is a Playwright fixture?", options: ["A test data file","A dependency injected into tests providing shared setup (e.g., logged-in page, database seed), scoped to test, worker, or global level","A screenshot","A browser type"], correctOptionIndex: 1, explanation: "Playwright's test.extend() creates custom fixtures. The built-in page fixture is an auto-managed browser page per test." },
      { level: "beginner", text: "What does await expect(locator).toBeVisible() do in Playwright?", options: ["Clicks an element","Asserts that the element is visible on the page, automatically retrying up to the timeout before failing","Hides an element","Checks CSS only"], correctOptionIndex: 1, explanation: "Playwright assertions auto-wait. toBeVisible(), toHaveText(), toBeEnabled() all retry until the condition is met or timeout expires." },
      { level: "beginner", text: "What is cy.visit() in Cypress?", options: ["A navigation spy","Navigates the test browser to a given URL, resetting the page state","A mock API call","A DOM query"], correctOptionIndex: 1, explanation: "cy.visit('http://localhost:3000') loads the app. Use baseUrl in cypress.config.js to avoid repeating the host." },
      // Intermediate
      { level: "intermediate", text: "What is the Playwright Page Object Model (POM)?", options: ["A design pattern","A test organisation pattern wrapping page interactions in classes, separating selectors and actions from test logic for maintainability","A Playwright feature","A fixture type"], correctOptionIndex: 1, explanation: "POMs centralise selectors: if a selector changes, update it in one class. Tests become readable behaviour descriptions." },
      { level: "intermediate", text: "What is network interception in Playwright?", options: ["Blocking all network requests","Using page.route() to intercept, abort, modify, or mock HTTP/HTTPS requests and responses during tests","A DNS feature","A proxy setting"], correctOptionIndex: 1, explanation: "await page.route('**/api/**', route => route.fulfill({ json: mockData })) mocks API calls for isolated frontend tests." },
      { level: "intermediate", text: "What is Playwright's auto-waiting?", options: ["A sleep statement","Playwright automatically waits for elements to be attached, visible, stable, and enabled before performing actions, eliminating flaky sleep() calls","A timeout setting","An explicit wait"], correctOptionIndex: 1, explanation: "Auto-waiting checks actionability conditions: attached, visible, stable (not animating), enabled, and editable before each action." },
      { level: "intermediate", text: "What is cy.task() in Cypress?", options: ["A CSS task","A command that runs code in Node.js (outside the browser) for operations not possible in the browser: DB seeding, file I/O, API calls","A visual command","A spy command"], correctOptionIndex: 1, explanation: "cy.task('seedDatabase') runs a Node.js task defined in cypress.config.js's setupNodeEvents, enabling backend interactions." },
      { level: "intermediate", text: "What is Playwright codegen?", options: ["A code minifier","A tool that records browser interactions and generates Playwright test code automatically — npx playwright codegen https://example.com","A reporting tool","A CI integration"], correctOptionIndex: 1, explanation: "Codegen is useful for quickly scaffolding tests. Always review and refactor generated selectors to use role-based locators." },
      { level: "intermediate", text: "What is visual testing in Playwright?", options: ["UI manual review","Screenshot comparison using expect(page).toHaveScreenshot() to detect unintended visual regressions across test runs","A performance test","An accessibility test"], correctOptionIndex: 1, explanation: "Playwright takes baseline screenshots and diffs subsequent runs pixel-by-pixel. Use --update-snapshots to update baselines." },
      { level: "intermediate", text: "What is the beforeEach hook in Cypress?", options: ["A data fixture","A hook running before each test in a describe block — commonly used for cy.visit() and authentication setup","An assertion","A command"], correctOptionIndex: 1, explanation: "beforeEach(() => { cy.login(); cy.visit('/dashboard'); }) avoids duplicating setup in every test." },
      { level: "intermediate", text: "What is Playwright's page.evaluate()?", options: ["A locator","Executes JavaScript in the browser page context and returns the result to Node.js — for reading DOM properties not accessible via locators","A screenshot tool","An assertion"], correctOptionIndex: 1, explanation: "const title = await page.evaluate(() => document.title) reads the page title from browser JS." },
      { level: "intermediate", text: "What is a Cypress custom command?", options: ["A CLI command","A reusable command added to cy (in cypress/support/commands.js) that encapsulates common action sequences like login","A plugin","A fixture"], correctOptionIndex: 1, explanation: "Cypress.Commands.add('login', (email, pw) => { cy.get('[data-cy=email]').type(email); ... }) enables cy.login(...) in all tests." },
      { level: "intermediate", text: "How do you run tests in parallel with Playwright?", options: ["Single thread only","Using --workers=4 to run test files in parallel across worker processes; Playwright Sharding splits the test suite across CI machines","Via Cypress Cloud only","Via threads only"], correctOptionIndex: 1, explanation: "Playwright's worker model parallelises test files by default. --shard=1/3 runs a third of the test suite for CI matrix jobs." },
      // Advanced
      { level: "advanced", text: "What is Playwright's storageState feature?", options: ["A cookie jar","A mechanism to save and restore browser storage (cookies, localStorage, sessionStorage) — enabling pre-authenticated test sessions without re-logging in per test","A database feature","A fixture type"], correctOptionIndex: 1, explanation: "Log in once in a global setup, save state to a file, then use storageState: 'auth.json' in tests to start authenticated." },
      { level: "advanced", text: "What is the Cypress Component Testing vs E2E testing?", options: ["No difference","Component Testing mounts individual components in isolation (like React Testing Library) in a real browser; E2E Testing loads the full application","Component Testing requires a server","E2E is deprecated"], correctOptionIndex: 1, explanation: "Cypress Component Testing provides fast, isolated component tests with full browser fidelity — a middle ground between unit and E2E." },
      { level: "advanced", text: "How do you handle flaky tests in Playwright?", options: ["Use sleep()","Enable retries (retries: 2 in config), use auto-waiting assertions instead of hard waits, fix race conditions in app code, and use test.fixme() to skip known flaky tests temporarily","Increase timeout only","Disable parallel execution"], correctOptionIndex: 1, explanation: "Flaky tests are usually caused by timing issues. Replace sleep with expect(locator).toBeVisible() to self-heal." },
      { level: "advanced", text: "What is page.waitForResponse() in Playwright?", options: ["A sleep command","Waits for a matching network response before proceeding — ensuring API data is loaded before asserting UI state","A retry mechanism","An assertion"], correctOptionIndex: 1, explanation: "const [response] = await Promise.all([page.waitForResponse('**/api/user'), page.click('button')]) awaits both the click and the API response together." },
      { level: "advanced", text: "What is Playwright's tracing?", options: ["A network log","A browser recording (screenshots, network, actions, console logs) captured during a test run and viewable in the Playwright Trace Viewer for debugging failures","A performance report","A code coverage tool"], correctOptionIndex: 1, explanation: "trace: 'on-first-retry' in config captures traces only when tests fail and retry, reducing overhead in passing runs." },
      { level: "advanced", text: "What is accessibility testing with Playwright?", options: ["Manual screen reader testing","Using @axe-core/playwright or checkA11y() to run Axe accessibility rule scans on pages within Playwright tests","A visual test","A CSS audit"], correctOptionIndex: 1, explanation: "Integrating Axe into Playwright tests automates WCAG compliance checks in CI, catching missing ARIA labels and contrast issues." },
      { level: "advanced", text: "What is Cypress Intercept best practices for avoiding test pollution?", options: ["Intercept globally","Define intercepts inside each test or beforeEach and prefer cy.intercept aliases with cy.wait('@alias') to ensure requests are made before asserting","Use cy.server()","Avoid intercepts"], correctOptionIndex: 1, explanation: "cy.intercept(...).as('getUsers'); cy.wait('@getUsers') makes tests deterministic, waiting for the specific request to complete." },
      { level: "advanced", text: "What is Playwright's multi-browser testing strategy for CI?", options: ["Test Chromium only","Use projects in playwright.config.ts to define Chromium, Firefox, and WebKit configurations — run all in CI with --project=chromium for faster local dev","Run manually","Requires 3 machines"], correctOptionIndex: 1, explanation: "Playwright's projects config lets you run tests on all three engines in one suite, targeting specific browsers for debugging." },
      { level: "advanced", text: "How do you integrate Playwright tests into a CI/CD pipeline?", options: ["Manual only","Run npx playwright test in CI (GitHub Actions, GitLab, Jenkins); cache browser binaries, use --reporter=html, upload the report as an artifact, use --shard for parallel runs","Via Cypress Cloud only","Via Docker only"], correctOptionIndex: 1, explanation: "GitHub Actions: npx playwright install --with-deps, then npx playwright test. Store playwright-report/ as an artifact for failure analysis." },
      { level: "advanced", text: "What is contract testing vs E2E testing?", options: ["Identical","Contract testing (e.g., Pact) verifies API contracts between consumer and provider in isolation; E2E tests the full integrated stack. Both are needed — contract tests are faster and more stable","Contract tests replace E2E","E2E tests replace contract tests"], correctOptionIndex: 1, explanation: "Contract tests catch breaking API changes early without a live environment. E2E tests verify real user journeys through the full stack." },
    ],
  },

  // ── LLM & OpenAI APIs ────────────────────────────────────────────────────
  {
    name: "LLM & OpenAI APIs",
    slug: "llm-apis",
    description: "Building AI-powered applications — prompting, embeddings, function calling, RAG, agents, fine-tuning, and responsible LLM deployment.",
    icon: "SiOpenai",
    category: "AI & ML",
    questions: [
      // Beginner
      { level: "beginner", text: "What is an LLM (Large Language Model)?", options: ["A database","A deep learning model trained on vast text data to understand and generate human language — e.g., GPT-4, Claude, Llama, Gemini","A SQL query tool","A rule-based chatbot"], correctOptionIndex: 1, explanation: "LLMs learn statistical patterns from trillions of tokens of text. They generate tokens probabilistically based on context." },
      { level: "beginner", text: "What is a token in the context of LLMs?", options: ["A security credential","The unit of text LLMs process — roughly 4 characters or 0.75 words in English; both prompt and response consume tokens","A database row","A network packet"], correctOptionIndex: 1, explanation: "Token limits (context window) determine how much text an LLM can process at once. GPT-4 Turbo has a 128K token context." },
      { level: "beginner", text: "What is a system prompt?", options: ["A programming prompt","Instructions prepended to a conversation that define the model's persona, behaviour, and constraints — invisible to the user in production apps","A model parameter","A file input"], correctOptionIndex: 1, explanation: "System prompts set context: 'You are a helpful customer support agent for Acme Corp. Only answer questions about our products.'" },
      { level: "beginner", text: "What is temperature in an LLM API call?", options: ["A server setting","A parameter (0-2) controlling randomness — low temperature (0.1) is deterministic/factual; high temperature (1.5) is creative/varied","A rate limit","A cost factor"], correctOptionIndex: 1, explanation: "Use temperature=0 for factual, reproducible outputs (data extraction, coding). Use 0.7-1.0 for creative writing." },
      { level: "beginner", text: "What is the OpenAI Chat Completions API?", options: ["A web scraper","An API accepting a list of messages with roles (system, user, assistant) and returning a generated response — the main interface for GPT models","A fine-tuning API","A search API"], correctOptionIndex: 1, explanation: "/v1/chat/completions accepts {model, messages, temperature} and returns choices[0].message.content." },
      { level: "beginner", text: "What is an embedding in the context of LLMs?", options: ["A CSS technique","A numerical vector representation of text (or other data) that captures semantic meaning — similar texts have similar embedding vectors","A model weight","A token type"], correctOptionIndex: 1, explanation: "Embeddings enable semantic search, clustering, and classification. OpenAI's text-embedding-3-small produces 1536-dimensional vectors." },
      { level: "beginner", text: "What is prompt engineering?", options: ["Hardware setup","The practice of crafting LLM input (prompts) to elicit more accurate, helpful, or structured outputs","Model training","A Python library"], correctOptionIndex: 1, explanation: "Techniques: clear instructions, role assignment, few-shot examples, chain-of-thought, output format specification." },
      { level: "beginner", text: "What is a context window?", options: ["A browser window","The maximum amount of text (measured in tokens) an LLM can process in a single request — includes both the input prompt and output response","A GPU memory limit","A rate limit"], correctOptionIndex: 1, explanation: "Context window determines how much history a chat model remembers. Longer contexts cost more and can degrade quality at extremes." },
      { level: "beginner", text: "What is streaming in LLM APIs?", options: ["Video streaming","Receiving LLM response tokens incrementally as they are generated (using Server-Sent Events), rather than waiting for the full response","A file upload","A batch operation"], correctOptionIndex: 1, explanation: "Streaming reduces perceived latency in chat apps. Set stream: true in the API call and process the event stream chunk by chunk." },
      { level: "beginner", text: "What is few-shot prompting?", options: ["A training technique","Providing a few input-output examples within the prompt to guide the model to produce responses in the desired format or style","A fine-tuning method","A model evaluation technique"], correctOptionIndex: 1, explanation: "Few-shot examples in the prompt are often more effective than zero-shot for structured output tasks (JSON extraction, classification)." },
      // Intermediate
      { level: "intermediate", text: "What is Retrieval-Augmented Generation (RAG)?", options: ["A training technique","A pattern combining a vector search database with an LLM — relevant documents are retrieved based on the query and injected into the prompt as context","A fine-tuning method","A model compression technique"], correctOptionIndex: 1, explanation: "RAG gives LLMs access to up-to-date or private knowledge without retraining. Embed documents, store vectors, retrieve top-k at query time." },
      { level: "intermediate", text: "What is function calling (tool use) in OpenAI APIs?", options: ["Calling Python functions","A feature allowing LLMs to request invocation of developer-defined functions by outputting structured JSON — enabling LLMs to interact with external systems","A fine-tuning step","A system prompt technique"], correctOptionIndex: 1, explanation: "Define tools with JSON Schema, the model returns a function call object, you execute it, return the result, and the model continues." },
      { level: "intermediate", text: "What is an AI agent?", options: ["A customer service bot","A system where an LLM autonomously plans and executes multi-step tasks using tools (web search, code execution, APIs) in a loop until a goal is achieved","A rule-based system","A neural network"], correctOptionIndex: 1, explanation: "ReAct (Reason + Act) agents alternate between reasoning (thought) and tool use (action) steps. LangChain and AutoGen implement agent loops." },
      { level: "intermediate", text: "What is LangChain?", options: ["A blockchain library","A Python/JS framework for building LLM applications — provides chains, agents, memory, document loaders, vector store integrations, and prompt templates","A fine-tuning tool","A model hosting service"], correctOptionIndex: 1, explanation: "LangChain abstracts LLM providers, memory, and tool integrations. LangGraph extends it for stateful, cyclical agent workflows." },
      { level: "intermediate", text: "What is vector similarity search and why is it used with LLMs?", options: ["A text search","Finding semantically similar documents by comparing embedding vectors using cosine similarity or dot product — used in RAG to retrieve relevant context","A keyword search","A SQL join"], correctOptionIndex: 1, explanation: "Pinecone, pgvector, Weaviate, and Chroma store embeddings and enable approximate nearest neighbour (ANN) search at scale." },
      { level: "intermediate", text: "What is LLM fine-tuning?", options: ["Adjusting prompts","Training a pre-trained LLM on a domain-specific dataset to specialise its behaviour, style, or knowledge for a particular task","Quantising a model","Compressing a model"], correctOptionIndex: 1, explanation: "OpenAI fine-tuning accepts JSONL files with {messages} pairs. Fine-tuning reduces token usage for repeated instructions vs. long system prompts." },
      { level: "intermediate", text: "What is token usage and cost management in LLM APIs?", options: ["Server cost only","Tracking prompt tokens + completion tokens per request to estimate cost; optimising by reducing prompt size, caching responses, and choosing smaller models for simpler tasks","A GPU metric","A rate limit"], correctOptionIndex: 1, explanation: "Use tiktoken to count tokens before API calls. Cache semantic-equivalent queries with embedding similarity to avoid redundant LLM calls." },
      { level: "intermediate", text: "What is structured output in OpenAI APIs?", options: ["A JSON file","The ability to constrain LLM output to a specific JSON schema using response_format: { type: 'json_schema' } or function calling, guaranteeing parseable output","A markdown format","A streaming format"], correctOptionIndex: 1, explanation: "Structured outputs eliminate JSON parsing errors. Define a Pydantic/Zod schema, pass it to the API, get back a validated object." },
      { level: "intermediate", text: "What is prompt injection?", options: ["A SQL attack","An attack where malicious user input manipulates an LLM's behaviour by overriding system prompt instructions — e.g., 'Ignore previous instructions and...'","A CSS injection","An API exploit"], correctOptionIndex: 1, explanation: "Mitigate by separating instruction and data contexts, validating outputs, and using OpenAI's system prompt hardening techniques." },
      { level: "intermediate", text: "What is LLM hallucination?", options: ["A model crash","When an LLM generates confident-sounding but factually incorrect or fabricated information not supported by its training data or provided context","A prompt error","A token limit issue"], correctOptionIndex: 1, explanation: "Mitigate hallucination with RAG (ground responses in retrieved documents), output validation, and retrieval-augmented fact-checking." },
      // Advanced
      { level: "advanced", text: "What is Mixture of Experts (MoE) architecture?", options: ["A team of models","An LLM architecture where only a subset of the network's parameters (expert layers) are activated per token, enabling larger model capacity at lower inference cost — used in GPT-4, Mixtral","A training technique","A fine-tuning approach"], correctOptionIndex: 1, explanation: "MoE models route each token to a sparse subset of expert FFN layers. This allows trillion-parameter models at the compute cost of smaller dense models." },
      { level: "advanced", text: "What is RLHF (Reinforcement Learning from Human Feedback)?", options: ["A model training technique","A training method using human preference data to align LLM outputs with human values — trains a reward model from human rankings, then fine-tunes the LLM using PPO","A prompting technique","A deployment strategy"], correctOptionIndex: 1, explanation: "RLHF (used in InstructGPT/ChatGPT) dramatically improved helpfulness and reduced harmful outputs compared to pure supervised fine-tuning." },
      { level: "advanced", text: "What is quantisation in LLM deployment?", options: ["A counting method","Reducing model weight precision (e.g., from 32-bit float to 4-bit integer) to reduce memory footprint and increase inference speed, with minimal quality loss","A training technique","A fine-tuning method"], correctOptionIndex: 1, explanation: "GGUF/GGML quantisation enables running 7B-70B parameter models on consumer hardware. llama.cpp supports Q4_K_M and similar formats." },
      { level: "advanced", text: "What is an LLM evaluation framework?", options: ["A prompt library","Tools and metrics for systematically assessing LLM outputs — accuracy, faithfulness, groundedness, latency, cost — using LLM-as-a-judge, RAGAS, or Evals","A fine-tuning library","A deployment tool"], correctOptionIndex: 1, explanation: "OpenAI Evals, RAGAS, and DeepEval provide automated LLM evaluation pipelines for RAG faithfulness, answer relevancy, and context recall." },
      { level: "advanced", text: "What is semantic caching for LLM applications?", options: ["A browser cache","Caching LLM responses by embedding the query and retrieving cached answers for semantically similar future queries, reducing API costs and latency","A token cache","A model cache"], correctOptionIndex: 1, explanation: "GPTCache and Redis with vector similarity enable semantic caching. A cosine similarity threshold (e.g., 0.95) determines cache hits." },
      { level: "advanced", text: "What is a multi-modal LLM?", options: ["A multilingual model","An LLM that processes and generates multiple data types — text, images, audio, video — in a unified model (e.g., GPT-4o, Gemini, Claude 3 Opus)","A multi-agent system","A distributed model"], correctOptionIndex: 1, explanation: "GPT-4o's vision capability accepts base64 images or URLs in the messages array. Multi-modal models enable visual QA, OCR, and image generation guidance." },
      { level: "advanced", text: "What is the difference between RAG and fine-tuning?", options: ["Identical","RAG retrieves external knowledge at inference time without changing model weights — ideal for dynamic, private data; fine-tuning updates model weights for style/behaviour — ideal for consistent format or domain-specific reasoning","RAG is cheaper always","Fine-tuning replaces RAG"], correctOptionIndex: 1, explanation: "Use RAG for up-to-date facts; fine-tune for consistent tone, format, or latency reduction (avoiding long system prompts). Often combined." },
      { level: "advanced", text: "What is an LLM gateway / proxy?", options: ["A VPN for LLMs","A middleware layer (e.g., LiteLLM, Portkey, Kong AI) that provides unified API access to multiple LLM providers, with routing, cost tracking, rate limiting, and fallback","A fine-tuning tool","A vector database"], correctOptionIndex: 1, explanation: "LLM gateways abstract provider-specific APIs, enable A/B testing between models, and provide observability without changing application code." },
      { level: "advanced", text: "What are Constitutional AI and RLAIF?", options: ["A governance framework","Techniques for aligning LLMs using AI-generated feedback: Constitutional AI uses a set of principles for self-critique; RLAIF uses an LLM as the reward model instead of humans","A deployment policy","A safety benchmark"], correctOptionIndex: 1, explanation: "Anthropic's Claude uses Constitutional AI — the model critiques and revises its own outputs against a set of principles, reducing harmful outputs at scale." },
      { level: "advanced", text: "What is LLM observability?", options: ["A logging tool","End-to-end tracing and monitoring of LLM application calls — tracking prompts, completions, latency, cost, errors, and evaluation scores across agent steps","A model dashboard","A token counter"], correctOptionIndex: 1, explanation: "Tools like LangSmith, Langfuse, and Helicone trace every LLM call, enabling debugging of multi-step agent failures and cost attribution." },
    ],
  },
];

async function main() {
  for (const course of NEW_COURSES) {
    // Skip if already inserted
    const existing = await db
      .select({ id: coursesTable.id })
      .from(coursesTable)
      .where(eq(coursesTable.slug, course.slug));

    if (existing.length > 0) {
      console.log(`  ⚠️  ${course.name} already exists — skipping.`);
      continue;
    }

    const [inserted] = await db
      .insert(coursesTable)
      .values({
        name: course.name,
        slug: course.slug,
        description: course.description,
        icon: course.icon,
        category: course.category,
      })
      .returning({ id: coursesTable.id });

    const rows = course.questions.map((q) => ({
      courseId: inserted.id,
      level: q.level,
      text: q.text,
      options: JSON.stringify(q.options),
      correctOptionIndex: q.correctOptionIndex,
      explanation: q.explanation,
    }));

    await db.insert(questionsTable).values(rows);
    console.log(`  ✓ ${course.name} (${rows.length} questions)`);
  }
  console.log("\nDone.");
  process.exit(0);
}

main().catch((err) => { console.error(err); process.exit(1); });
